In [35]:
from plotly.offline import init_notebook_mode, iplot
from IPython.display import display, HTML
from plotly.graph_objs import Histogram as H
import plotly.plotly as py
import pandas as pd
import numpy as np
init_notebook_mode(connected=True)
import plotly.graph_objs as go
from datetime import datetime
import seaborn as sns

In [4]:
canteen2 = pd.read_csv('../Data/cafeteria_dilemma_2.csv')

canteen2.columns



Index(['participant.id_in_session', 'participant.code', 'participant.label',
       'participant._is_bot', 'participant._index_in_pages',
       'participant._max_page_index', 'participant._current_app_name',
       'participant._round_number', 'participant._current_page_name',
       'participant.ip_address', 'participant.time_started',
       'participant.exclude_from_data_analysis', 'participant.visited',
       'participant.mturk_worker_id', 'participant.mturk_assignment_id',
       'participant.payoff', 'player.id_in_group', 'player.arrival_time',
       'player.choice', 'player.strategy_cafeteria_dilemma',
       'player.common_knowledge', 'player.certainty', 'player.payoff',
       'group.id_in_subsession', 'group.payoff', 'group.game_lost',
       'subsession.round_number', 'session.code', 'session.label',
       'session.experimenter_name', 'session.mturk_HITId',
       'session.mturk_HITGroupId', 'session.comment', 'session.is_demo'],
      dtype='object')

In [5]:
round1_df = canteen2[canteen2["subsession.round_number"]==1]

In [113]:
round1_df["player.choice"]

0        Office
1     Cafeteria
2        Office
3        Office
4     Cafeteria
5     Cafeteria
6     Cafeteria
7     Cafeteria
8        Office
9        Office
10       Office
11    Cafeteria
12       Office
13       Office
14       Office
15    Cafeteria
16    Cafeteria
17       Office
18    Cafeteria
19    Cafeteria
20    Cafeteria
21    Cafeteria
22    Cafeteria
23       Office
Name: player.choice, dtype: object

In [114]:
np.unique(canteen2['player.arrival_time'])

array([8.31, 8.32, 8.33, 8.35, 8.36, 8.37, 8.38, 8.39, 8.4 , 8.41, 8.42,
       8.43, 8.44, 8.45, 8.46, 8.47, 8.48, 8.49, 8.5 , 8.51, 8.52, 8.53,
       8.54, 8.55, 8.56, 8.57, 8.58, 8.59, 9.  , 9.01, 9.02, 9.03, 9.04,
       9.05, 9.06, 9.08, 9.09])

In [6]:
#arrival for cafeteria
round1_df[round1_df["player.choice"]=="Cafeteria"]["player.arrival_time"]

1     8.52
4     8.49
5     8.44
6     8.49
7     8.54
11    8.47
15    8.55
16    9.02
18    8.36
19    8.31
20    8.38
21    8.43
22    8.53
Name: player.arrival_time, dtype: float64

In [7]:
round1_cafeteria_time = round1_df["player.arrival_time"]
np.sort(round1_cafeteria_time)

array([8.31, 8.36, 8.38, 8.43, 8.44, 8.47, 8.49, 8.49, 8.52, 8.52, 8.53,
       8.53, 8.54, 8.55, 8.55, 8.57, 8.57, 9.01, 9.02, 9.04, 9.05, 9.05,
       9.06, 9.09])

In [8]:
round1_office_time = round1_df[round1_df["player.choice"]=="Office"]["player.arrival_time"]
round1_office_time

0     8.57
2     9.01
3     9.06
8     9.05
9     9.05
10    8.52
12    9.04
13    9.09
14    8.55
17    8.57
23    8.53
Name: player.arrival_time, dtype: float64

In [120]:
round1_cafeteria_time = round1_df[round1_df["player.choice"]=="Cafeteria"]["player.arrival_time"]
round1_cafeteria_time

1     8.52
4     8.49
5     8.44
6     8.49
7     8.54
11    8.47
15    8.55
16    9.02
18    8.36
19    8.31
20    8.38
21    8.43
22    8.53
Name: player.arrival_time, dtype: float64

In [99]:
round1_df["player.arrival_time"]

0     8.57
1     8.52
2     9.01
3     9.06
4     8.49
5     8.44
6     8.49
7     8.54
8     9.05
9     9.05
10    8.52
11    8.47
12    9.04
13    9.09
14    8.55
15    8.55
16    9.02
17    8.57
18    8.36
19    8.31
20    8.38
21    8.43
22    8.53
23    8.53
Name: player.arrival_time, dtype: float64

In [ ]:
import pylab as pl
>>> pl.frange(0.5,5,0.5)
array([ 0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ])

In [31]:
office_df = canteen2[canteen2["player.choice"]=="Office"]
np.unique(office_df["player.arrival_time"])
index_list=[]
for time in np.sort(office_df["player.arrival_time"]):
    index_list.append(sum(np.sort(office_df["player.arrival_time"])==time))

index_list

[1,
 2,
 2,
 2,
 2,
 1,
 3,
 3,
 3,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 8,
 4,
 4,
 4,
 4,
 2,
 2,
 2,
 2,
 5,
 5,
 5,
 5,
 5,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 12,
 4,
 4,
 4,
 4,
 7,
 7,
 7,
 7,
 7,
 7,
 7,
 4,
 4,
 4,
 4,
 5,
 5,
 5,
 5,
 5,
 3,
 3,
 3,
 2,
 2,
 2,
 2]

In [33]:
list(np.sort(office_df["player.arrival_time"]))

[8.51,
 8.52,
 8.52,
 8.53,
 8.53,
 8.54,
 8.55,
 8.55,
 8.55,
 8.56,
 8.56,
 8.56,
 8.56,
 8.56,
 8.56,
 8.56,
 8.56,
 8.57,
 8.57,
 8.57,
 8.57,
 8.58,
 8.58,
 8.59,
 8.59,
 9.0,
 9.0,
 9.0,
 9.0,
 9.0,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.01,
 9.02,
 9.02,
 9.02,
 9.02,
 9.03,
 9.03,
 9.03,
 9.03,
 9.03,
 9.03,
 9.03,
 9.04,
 9.04,
 9.04,
 9.04,
 9.05,
 9.05,
 9.05,
 9.05,
 9.05,
 9.06,
 9.06,
 9.06,
 9.08,
 9.08,
 9.09,
 9.09]

In [37]:
trace1 = go.Bar(
    x=list(np.sort(office_df["player.arrival_time"])),
    y=index_list,
    name='Office',
    marker=dict(
        color='rgb(55, 83, 109)'
    )
)

data=[trace1]
fig = go.Figure(data=data)
py.iplot(fig, filename='style-bar')

C:\Users\Thomas\Miniconda3\envs\py37viz\lib\site-packages\IPython\core\display.py:689: UserWarning:

Consider using IPython.display.IFrame instead



In [9]:
metascore_color = "#ffd263"
userscore_color = "#62d5ff"
new_data_list=[]
bar_opacity = 0.8
bin_size=0.1
data=[]
choice_trace = go.Histogram(
            visible = True,
            x=round1_cafeteria_time,
            ##ADD/REMOVE HISTNORM FOR NORMALISING
            histnorm='',
            #histnorm='percent',
            name='Cafeteria',
            xbins=dict(
                start=8,
                end=9.1,
                size=bin_size
            ),
            marker=dict(
                color=metascore_color,
            ),
            opacity=bar_opacity
        )
data.append(choice_trace)
office_trace = go.Histogram(
            visible = True,
            x=round1_office_time,
            ##ADD/REMOVE HISTNORM FOR NORMALISING
            histnorm='',
            #histnorm='percent',
            name='Office',
            xbins=dict(
                start=8,
                end=9.1,
                size=bin_size
            ),
            marker=dict(
                color=userscore_color,
            ),
            opacity=bar_opacity
        )
data.append(office_trace)

layout = dict(
    yaxis=dict(
        range=[0, 5],
        title='Count'
    ),
    xaxis=dict(
        range=[8, 11],
        title='Userscore and metascores in bins of 5'
    ),
    barmode="overlay"
    )
fig = dict(data=data)

py.iplot(fig, filename='Cafeteria plot')

C:\Users\Thomas\Miniconda3\envs\py37viz\lib\site-packages\IPython\core\display.py:689: UserWarning:

Consider using IPython.display.IFrame instead



In [ ]:
#init some variables
years = list(range(2000, 2019))
#metascore_color = "#8da0cb"
#userscore_color = "#fc8d62"
#Orange: #ffd263
#Blue: #62d5ff
metascore_color = "#ffd263"
userscore_color = "#62d5ff"
new_data_list=[]
bar_opacity = 0.8
bin_size=5

## make datatraces and append to datalist
for year in years:   
    year_metatrace = go.Histogram(
            visible = False,
            x=meta_games_years[year]['metascore'],
            ##ADD/REMOVE HISTNORM FOR NORMALISING
            histnorm='',
            #histnorm='percent',
            name='metascore',
            xbins=dict(
                start=0,
                end=100,
                size=bin_size
            ),
            marker=dict(
                color=metascore_color,
            ),
            opacity=bar_opacity
        )
    year_usertrace = go.Histogram(
            visible = False,
            x=meta_games_years[year]['userscore'].astype(float) * 10,
            ##ADD/REMOVE HISTNORM FOR NORMALISING
            histnorm='',
            #histnorm='percent',
            name='userscore',
            xbins=dict(
                start=0,
                end=100,
                size=bin_size
            ),
            marker=dict(
                color=userscore_color,
            ),
            opacity=bar_opacity
        )
    
    
    new_data_list.append(year_metatrace)
    new_data_list.append(year_usertrace)
    #new_data_list.append(meta_mean) #only for mean of metascore
    
    
new_data_list[0]['visible']=True
new_data_list[1]['visible']=True

#new_data_list[2]['visible']=True #metascore mean



#list of bools for determining what trace to show as visible in 'args'
data_bools = []
for i in range(0, len(new_data_list), 2):
    temp_big_bool = len(new_data_list) * [False]
    temp_big_bool[i] = True
    temp_big_bool[i + 1] = True
    data_bools.append(temp_big_bool)